import { Afacad } from "next/font/google";
import "./globals.css";
import Header from "./Header";
import { Footerr } from "./Footer";

const afacad = Afacad({
  variable: "--font-afacad",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body
        className={`${afacad.className} antialiased`}
      >
        <Header />
        {children}
        <Footerr />
      </body>
    </html>
  );
}
